---
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
  name: clickhouse
- src: clickhouse-role
  name: clickhouse-role
- src: vector-role
  name: vector-role
- src: lighthouse-role
  name: lighthouse-role
