#SPDX-License-Identifier: MIT-0
---
# handlers file for clickhouse-role

- name: Start clickhouse service
  become: true
  ansible.builtin.service:
    name: "{{ clickhouse_service_name }}"
    state: restarted
