#SPDX-License-Identifier: MIT-0
---
# tasks file for lighthouse-role

- name: Install nginx
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Create directory for lighthouse
  become: true
  ansible.builtin.file:
    path: "{{ lighthouse_nginx_root }}"
    state: directory
    mode: "0755"

- name: Download lighthouse static files
  ansible.builtin.get_url:
    url: "{{ lighthouse_zip_url }}"
    dest: "{{ lighthouse_zip_path }}"
    mode: "0644"

- name: Install unzip package
  become: true
  ansible.builtin.yum:
    name: unzip
    state: present

- name: Unzip lighthouse files
  become: true
  ansible.builtin.command:
    cmd: "unzip -o {{ lighthouse_zip_path }} -d {{ lighthouse_nginx_root }}"
  args:
    creates: "{{ lighthouse_nginx_root }}/index.html"

- name: Configure nginx
  become: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ lighthouse_nginx_conf_path }}"
    mode: "0644"
  notify: Restart nginx

- name: Start and enable nginx
  become: true
  ansible.builtin.service:
    name: "{{ lighthouse_nginx_service }}"
    state: started
    enabled: yes
