#SPDX-License-Identifier: MIT-0
---
# tasks file for vector-role

- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ vector_architecture }}.rpm"
    dest: "/tmp/vector-{{ vector_version }}-1.{{ vector_architecture }}.rpm"
    mode: "0644"

- name: Install vector
  become: true
  ansible.builtin.yum:
    disable_gpg_check: true
    name:
      - /tmp/vector-{{ vector_version }}-1.{{ vector_architecture }}.rpm

- name: Deploy Vector configuration
  become: true
  ansible.builtin.template:
    src: vector.toml.j2
    dest: "{{ vector_config_path }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart Vector

- name: Enable and start Vector service
  become: true
  ansible.builtin.service:
    name: "{{ vector_service_name }}"
    state: started
    enabled: yes
